provider: google

google:
  project: "fedv2-218905"
  serviceAccountSecret: "gcloud-config"

sources:
  - crd

extraArgs:
  crd-source-apiversion: multiclusterdns.federation.k8s.io/v1alpha1
  crd-source-kind: DNSEndpoint

registry: "noop"
