apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: fs1
spec:
  template:
    spec:
      selector:
        app: demo
      ports:
      - protocol: TCP
        port: 80
        targetPort: 80
      type: LoadBalancer
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: fs1
spec:
  clusterSelector: {}
