apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedReplicaSet
metadata:
  name: fr1
spec:
  template:
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: demo
      template:
        metadata:
          name: demo
          labels:
            app: demo
        spec:
          containers:
          - name: demo
            image: shashidharatd/fed-sd-demo
            ports:
            - containerPort: 80
            env:
              - name: MY_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MY_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: MY_POD_SERVICE_ACCOUNT
                valueFrom:
                  fieldRef:
                    fieldPath: spec.serviceAccountName
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedReplicaSetPlacement
metadata:
  name: fr1
spec:
  clusterNames:
  - cluster1
  - cluster2
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedReplicaSetOverride
metadata:
  name: fr1
spec:
  overrides:
  - clusterName: cluster2
    replicas: 3
